server:
    port: ${PORT:8081}

spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/vendas
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect

veiculos:
    service:
        url: ${URL_VEICULO_SERVICE}
        auth-token: ${AUTH_TOKEN}

stripe:
    api:
        secretKey: ${SECRET_KEY}
    webhook:
        secret: whsec_8puE5Tzv2NANSVGWq5Sw7jQdzf3YBePJ

