server:
    port: 8081

spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/vendas
        username: veiculo_adm
        password: ead@2025
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect

veiculos:
    service:
        url: http://localhost:8080